Repository LedgerHQ/wallet-api, pull requests merged in 2023-01, with the labels that each got.

#91 added wallet info and user id
  .changeset/mighty-hats-pump.md
  packages/client/src/WalletAPIClient.ts
  packages/client/src/modules/Bitcoin.ts
  packages/client/src/modules/Wallet.ts
  packages/core/src/spec/methods.ts
  packages/core/src/spec/rpcHandlers/WalletHandlers.ts
  packages/core/src/spec/types/WalletInfo.ts
  packages/core/src/spec/types/WalletUserId.ts
  packages/core/src/spec/types/index.ts
  packages/server/src/WalletAPIServer.ts
  packages/server/src/internalHandlers/index.ts
  packages/server/src/internalHandlers/wallet.ts
  packages/server/src/types.ts
  packages/simulator/src/profiles/standard/index.ts
  packages/simulator/src/test-run.ts
  packages/simulator/src/transport.ts
  packages/simulator/src/types.ts
  website/docs/reference/api/client/classes/WalletAPIClient.md
  website/docs/reference/api/client/index.md
  website/docs/reference/api/client/interfaces/WalletHandlers.md
  website/docs/reference/api/server/classes/WalletAPIServer.md
  website/docs/reference/api/server/index.md
  website/docs/reference/api/server/interfaces/WalletHandlers.md
Labels: enhancement

#48 LIVE-5086: added a first storage draft
  .changeset/loud-windows-fetch.md
  packages/client/src/WalletAPIClient.ts
  packages/client/src/modules/Storage.ts
  packages/core/src/spec/rpcHandlers/WalletHandlers.ts
  packages/core/src/spec/types/StorageGet.ts
  packages/core/src/spec/types/StorageSet.ts
  packages/core/src/spec/types/index.ts
  packages/server/src/internalHandlers/index.ts
  packages/server/src/internalHandlers/storage.ts
  packages/server/src/types.ts
  packages/simulator/src/profiles/standard/index.ts
  packages/simulator/src/transport.ts
  website/docs/reference/api/client/classes/WalletAPIClient.md
  website/docs/reference/api/client/index.md
  website/docs/reference/api/client/interfaces/WalletHandlers.md
  website/docs/reference/api/server/index.md
  website/docs/reference/api/server/interfaces/WalletHandlers.md
Labels: enhancement, platform-stuff

#101 chore: fix website turborepo setup
  package.json
  pnpm-lock.yaml
  turbo.json
  website/package.json
Labels: enhancement, github-monorepo

#102 refactor: client into modules
  .changeset/nine-needles-know.md
  packages/client/src/WalletAPIClient.ts
  packages/client/src/modules/Account.ts
  packages/client/src/modules/Currency.ts
  packages/client/src/modules/Device.ts
  packages/client/src/modules/Message.ts
  packages/client/src/modules/Transaction.ts
  website/docs/reference/api/client/classes/WalletAPIClient.md
  website/docs/reference/api/client/index.md
  website/docs/reference/api/client/interfaces/TransactionCommon.md
Labels: enhancement, client
